import type { PhotoSlot } from "@/lib/photo-slots";

// Type-only import: photo-slots.ts imports this file's data.

/**
 * The Little Years toddler book: 146 photo slots (140 at 4x4, 6 at 5x5), one
 * intro photo then the same 29-slot template for Ages One to Five. Boy and
 * Girl share this layout (window count, size and order checked 2026-10-02).
 *
 * GENERATED from seo-builds/2026-10-01-review-collection/
 * little-years-boy-slots-measured.json by
 * audits/photo-lab-little-years-2026-10-02/gen_little_years_slots.py.
 * Edit the JSON and regenerate rather than editing by hand.
 */
export const LITTLE_YEARS_SLOTS: PhotoSlot[] = [
  { key: "ly_story", prompt: "This Is the Story Of", size: "5x5", section: "ly_intro", sectionLabel: "This Is the Story Of", sortOrder: 1, page: 1 },
  { key: "ly_a1_birthday_1", prompt: "1st Birthday", size: "4x4", section: "ly_a1_birthday", sectionLabel: "Your 1st Birthday", sortOrder: 2, page: 2, group: "Age One" },
  { key: "ly_a1_birthday_2", prompt: "1st Birthday", size: "4x4", section: "ly_a1_birthday", sectionLabel: "Your 1st Birthday", sortOrder: 3, page: 2, group: "Age One" },
  { key: "ly_a1_birthday_3", prompt: "1st Birthday", size: "4x4", section: "ly_a1_birthday", sectionLabel: "Your 1st Birthday", sortOrder: 4, page: 2, group: "Age One" },
  { key: "ly_a1_grown_1", prompt: "Look How You've Grown", size: "4x4", section: "ly_a1_grown", sectionLabel: "Look How You've Grown", sortOrder: 5, page: 3, group: "Age One" },
  { key: "ly_a1_grown_2", prompt: "Look How You've Grown", size: "4x4", section: "ly_a1_grown", sectionLabel: "Look How You've Grown", sortOrder: 6, page: 3, group: "Age One" },
  { key: "ly_a1_grown_3", prompt: "Look How You've Grown", size: "4x4", section: "ly_a1_grown", sectionLabel: "Look How You've Grown", sortOrder: 7, page: 3, group: "Age One" },
  { key: "ly_a1_family", prompt: "Our Family, Age One", size: "5x5", section: "ly_a1_family", sectionLabel: "Our Family", sortOrder: 8, page: 6, group: "Age One" },
  { key: "ly_a1_holiday_1", prompt: "Holiday ___", size: "4x4", section: "ly_a1_holidays", sectionLabel: "Holidays", sortOrder: 9, page: 8, group: "Age One", customLabel: true },
  { key: "ly_a1_holiday_2", prompt: "Holiday ___", size: "4x4", section: "ly_a1_holidays", sectionLabel: "Holidays", sortOrder: 10, page: 8, group: "Age One", customLabel: true },
  { key: "ly_a1_holiday_3", prompt: "Holiday ___", size: "4x4", section: "ly_a1_holidays", sectionLabel: "Holidays", sortOrder: 11, page: 8, group: "Age One", customLabel: true },
  { key: "ly_a1_holiday_4", prompt: "Holiday ___", size: "4x4", section: "ly_a1_holidays", sectionLabel: "Holidays", sortOrder: 12, page: 9, group: "Age One", customLabel: true },
  { key: "ly_a1_holiday_5", prompt: "Holiday ___", size: "4x4", section: "ly_a1_holidays", sectionLabel: "Holidays", sortOrder: 13, page: 9, group: "Age One", customLabel: true },
  { key: "ly_a1_holiday_6", prompt: "Holiday ___", size: "4x4", section: "ly_a1_holidays", sectionLabel: "Holidays", sortOrder: 14, page: 9, group: "Age One", customLabel: true },
  { key: "ly_a1_snapshot_1", prompt: "Snapshot 1", size: "4x4", section: "ly_a1_snapshots", sectionLabel: "Snapshots of You", sortOrder: 15, page: 10, group: "Age One" },
  { key: "ly_a1_snapshot_2", prompt: "Snapshot 2", size: "4x4", section: "ly_a1_snapshots", sectionLabel: "Snapshots of You", sortOrder: 16, page: 10, group: "Age One" },
  { key: "ly_a1_snapshot_3", prompt: "Snapshot 3", size: "4x4", section: "ly_a1_snapshots", sectionLabel: "Snapshots of You", sortOrder: 17, page: 10, group: "Age One" },
  { key: "ly_a1_snapshot_4", prompt: "Snapshot 4", size: "4x4", section: "ly_a1_snapshots", sectionLabel: "Snapshots of You", sortOrder: 18, page: 10, group: "Age One" },
  { key: "ly_a1_snapshot_5", prompt: "Snapshot 5", size: "4x4", section: "ly_a1_snapshots", sectionLabel: "Snapshots of You", sortOrder: 19, page: 11, group: "Age One" },
  { key: "ly_a1_snapshot_6", prompt: "Snapshot 6", size: "4x4", section: "ly_a1_snapshots", sectionLabel: "Snapshots of You", sortOrder: 20, page: 11, group: "Age One" },
  { key: "ly_a1_snapshot_7", prompt: "Snapshot 7", size: "4x4", section: "ly_a1_snapshots", sectionLabel: "Snapshots of You", sortOrder: 21, page: 11, group: "Age One" },
  { key: "ly_a1_snapshot_8", prompt: "Snapshot 8", size: "4x4", section: "ly_a1_snapshots", sectionLabel: "Snapshots of You", sortOrder: 22, page: 11, group: "Age One" },
  { key: "ly_a1_snapshot_9", prompt: "Snapshot 9", size: "4x4", section: "ly_a1_snapshots", sectionLabel: "Snapshots of You", sortOrder: 23, page: 12, group: "Age One" },
  { key: "ly_a1_snapshot_10", prompt: "Snapshot 10", size: "4x4", section: "ly_a1_snapshots", sectionLabel: "Snapshots of You", sortOrder: 24, page: 12, group: "Age One" },
  { key: "ly_a1_snapshot_11", prompt: "Snapshot 11", size: "4x4", section: "ly_a1_snapshots", sectionLabel: "Snapshots of You", sortOrder: 25, page: 12, group: "Age One" },
  { key: "ly_a1_snapshot_12", prompt: "Snapshot 12", size: "4x4", section: "ly_a1_snapshots", sectionLabel: "Snapshots of You", sortOrder: 26, page: 12, group: "Age One" },
  { key: "ly_a1_snapshot_13", prompt: "Snapshot 13", size: "4x4", section: "ly_a1_snapshots", sectionLabel: "Snapshots of You", sortOrder: 27, page: 13, group: "Age One" },
  { key: "ly_a1_snapshot_14", prompt: "Snapshot 14", size: "4x4", section: "ly_a1_snapshots", sectionLabel: "Snapshots of You", sortOrder: 28, page: 13, group: "Age One" },
  { key: "ly_a1_snapshot_15", prompt: "Snapshot 15", size: "4x4", section: "ly_a1_snapshots", sectionLabel: "Snapshots of You", sortOrder: 29, page: 13, group: "Age One" },
  { key: "ly_a1_snapshot_16", prompt: "Snapshot 16", size: "4x4", section: "ly_a1_snapshots", sectionLabel: "Snapshots of You", sortOrder: 30, page: 13, group: "Age One" },
  { key: "ly_a2_birthday_1", prompt: "2nd Birthday", size: "4x4", section: "ly_a2_birthday", sectionLabel: "Your 2nd Birthday", sortOrder: 31, page: 23, group: "Age Two" },
  { key: "ly_a2_birthday_2", prompt: "2nd Birthday", size: "4x4", section: "ly_a2_birthday", sectionLabel: "Your 2nd Birthday", sortOrder: 32, page: 23, group: "Age Two" },
  { key: "ly_a2_birthday_3", prompt: "2nd Birthday", size: "4x4", section: "ly_a2_birthday", sectionLabel: "Your 2nd Birthday", sortOrder: 33, page: 23, group: "Age Two" },
  { key: "ly_a2_grown_1", prompt: "Look How You've Grown", size: "4x4", section: "ly_a2_grown", sectionLabel: "Look How You've Grown", sortOrder: 34, page: 24, group: "Age Two" },
  { key: "ly_a2_grown_2", prompt: "Look How You've Grown", size: "4x4", section: "ly_a2_grown", sectionLabel: "Look How You've Grown", sortOrder: 35, page: 24, group: "Age Two" },
  { key: "ly_a2_grown_3", prompt: "Look How You've Grown", size: "4x4", section: "ly_a2_grown", sectionLabel: "Look How You've Grown", sortOrder: 36, page: 24, group: "Age Two" },
  { key: "ly_a2_family", prompt: "Our Family, Age Two", size: "5x5", section: "ly_a2_family", sectionLabel: "Our Family", sortOrder: 37, page: 27, group: "Age Two" },
  { key: "ly_a2_holiday_1", prompt: "Holiday ___", size: "4x4", section: "ly_a2_holidays", sectionLabel: "Holidays", sortOrder: 38, page: 29, group: "Age Two", customLabel: true },
  { key: "ly_a2_holiday_2", prompt: "Holiday ___", size: "4x4", section: "ly_a2_holidays", sectionLabel: "Holidays", sortOrder: 39, page: 29, group: "Age Two", customLabel: true },
  { key: "ly_a2_holiday_3", prompt: "Holiday ___", size: "4x4", section: "ly_a2_holidays", sectionLabel: "Holidays", sortOrder: 40, page: 29, group: "Age Two", customLabel: true },
  { key: "ly_a2_holiday_4", prompt: "Holiday ___", size: "4x4", section: "ly_a2_holidays", sectionLabel: "Holidays", sortOrder: 41, page: 30, group: "Age Two", customLabel: true },
  { key: "ly_a2_holiday_5", prompt: "Holiday ___", size: "4x4", section: "ly_a2_holidays", sectionLabel: "Holidays", sortOrder: 42, page: 30, group: "Age Two", customLabel: true },
  { key: "ly_a2_holiday_6", prompt: "Holiday ___", size: "4x4", section: "ly_a2_holidays", sectionLabel: "Holidays", sortOrder: 43, page: 30, group: "Age Two", customLabel: true },
  { key: "ly_a2_snapshot_1", prompt: "Snapshot 1", size: "4x4", section: "ly_a2_snapshots", sectionLabel: "Snapshots of You", sortOrder: 44, page: 31, group: "Age Two" },
  { key: "ly_a2_snapshot_2", prompt: "Snapshot 2", size: "4x4", section: "ly_a2_snapshots", sectionLabel: "Snapshots of You", sortOrder: 45, page: 31, group: "Age Two" },
  { key: "ly_a2_snapshot_3", prompt: "Snapshot 3", size: "4x4", section: "ly_a2_snapshots", sectionLabel: "Snapshots of You", sortOrder: 46, page: 31, group: "Age Two" },
  { key: "ly_a2_snapshot_4", prompt: "Snapshot 4", size: "4x4", section: "ly_a2_snapshots", sectionLabel: "Snapshots of You", sortOrder: 47, page: 31, group: "Age Two" },
  { key: "ly_a2_snapshot_5", prompt: "Snapshot 5", size: "4x4", section: "ly_a2_snapshots", sectionLabel: "Snapshots of You", sortOrder: 48, page: 32, group: "Age Two" },
  { key: "ly_a2_snapshot_6", prompt: "Snapshot 6", size: "4x4", section: "ly_a2_snapshots", sectionLabel: "Snapshots of You", sortOrder: 49, page: 32, group: "Age Two" },
  { key: "ly_a2_snapshot_7", prompt: "Snapshot 7", size: "4x4", section: "ly_a2_snapshots", sectionLabel: "Snapshots of You", sortOrder: 50, page: 32, group: "Age Two" },
  { key: "ly_a2_snapshot_8", prompt: "Snapshot 8", size: "4x4", section: "ly_a2_snapshots", sectionLabel: "Snapshots of You", sortOrder: 51, page: 32, group: "Age Two" },
  { key: "ly_a2_snapshot_9", prompt: "Snapshot 9", size: "4x4", section: "ly_a2_snapshots", sectionLabel: "Snapshots of You", sortOrder: 52, page: 33, group: "Age Two" },
  { key: "ly_a2_snapshot_10", prompt: "Snapshot 10", size: "4x4", section: "ly_a2_snapshots", sectionLabel: "Snapshots of You", sortOrder: 53, page: 33, group: "Age Two" },
  { key: "ly_a2_snapshot_11", prompt: "Snapshot 11", size: "4x4", section: "ly_a2_snapshots", sectionLabel: "Snapshots of You", sortOrder: 54, page: 33, group: "Age Two" },
  { key: "ly_a2_snapshot_12", prompt: "Snapshot 12", size: "4x4", section: "ly_a2_snapshots", sectionLabel: "Snapshots of You", sortOrder: 55, page: 33, group: "Age Two" },
  { key: "ly_a2_snapshot_13", prompt: "Snapshot 13", size: "4x4", section: "ly_a2_snapshots", sectionLabel: "Snapshots of You", sortOrder: 56, page: 34, group: "Age Two" },
  { key: "ly_a2_snapshot_14", prompt: "Snapshot 14", size: "4x4", section: "ly_a2_snapshots", sectionLabel: "Snapshots of You", sortOrder: 57, page: 34, group: "Age Two" },
  { key: "ly_a2_snapshot_15", prompt: "Snapshot 15", size: "4x4", section: "ly_a2_snapshots", sectionLabel: "Snapshots of You", sortOrder: 58, page: 34, group: "Age Two" },
  { key: "ly_a2_snapshot_16", prompt: "Snapshot 16", size: "4x4", section: "ly_a2_snapshots", sectionLabel: "Snapshots of You", sortOrder: 59, page: 34, group: "Age Two" },
  { key: "ly_a3_birthday_1", prompt: "3rd Birthday", size: "4x4", section: "ly_a3_birthday", sectionLabel: "Your 3rd Birthday", sortOrder: 60, page: 44, group: "Age Three" },
  { key: "ly_a3_birthday_2", prompt: "3rd Birthday", size: "4x4", section: "ly_a3_birthday", sectionLabel: "Your 3rd Birthday", sortOrder: 61, page: 44, group: "Age Three" },
  { key: "ly_a3_birthday_3", prompt: "3rd Birthday", size: "4x4", section: "ly_a3_birthday", sectionLabel: "Your 3rd Birthday", sortOrder: 62, page: 44, group: "Age Three" },
  { key: "ly_a3_grown_1", prompt: "Look How You've Grown", size: "4x4", section: "ly_a3_grown", sectionLabel: "Look How You've Grown", sortOrder: 63, page: 45, group: "Age Three" },
  { key: "ly_a3_grown_2", prompt: "Look How You've Grown", size: "4x4", section: "ly_a3_grown", sectionLabel: "Look How You've Grown", sortOrder: 64, page: 45, group: "Age Three" },
  { key: "ly_a3_grown_3", prompt: "Look How You've Grown", size: "4x4", section: "ly_a3_grown", sectionLabel: "Look How You've Grown", sortOrder: 65, page: 45, group: "Age Three" },
  { key: "ly_a3_family", prompt: "Our Family, Age Three", size: "5x5", section: "ly_a3_family", sectionLabel: "Our Family", sortOrder: 66, page: 48, group: "Age Three" },
  { key: "ly_a3_holiday_1", prompt: "Holiday ___", size: "4x4", section: "ly_a3_holidays", sectionLabel: "Holidays", sortOrder: 67, page: 50, group: "Age Three", customLabel: true },
  { key: "ly_a3_holiday_2", prompt: "Holiday ___", size: "4x4", section: "ly_a3_holidays", sectionLabel: "Holidays", sortOrder: 68, page: 50, group: "Age Three", customLabel: true },
  { key: "ly_a3_holiday_3", prompt: "Holiday ___", size: "4x4", section: "ly_a3_holidays", sectionLabel: "Holidays", sortOrder: 69, page: 50, group: "Age Three", customLabel: true },
  { key: "ly_a3_holiday_4", prompt: "Holiday ___", size: "4x4", section: "ly_a3_holidays", sectionLabel: "Holidays", sortOrder: 70, page: 51, group: "Age Three", customLabel: true },
  { key: "ly_a3_holiday_5", prompt: "Holiday ___", size: "4x4", section: "ly_a3_holidays", sectionLabel: "Holidays", sortOrder: 71, page: 51, group: "Age Three", customLabel: true },
  { key: "ly_a3_holiday_6", prompt: "Holiday ___", size: "4x4", section: "ly_a3_holidays", sectionLabel: "Holidays", sortOrder: 72, page: 51, group: "Age Three", customLabel: true },
  { key: "ly_a3_snapshot_1", prompt: "Snapshot 1", size: "4x4", section: "ly_a3_snapshots", sectionLabel: "Snapshots of You", sortOrder: 73, page: 52, group: "Age Three" },
  { key: "ly_a3_snapshot_2", prompt: "Snapshot 2", size: "4x4", section: "ly_a3_snapshots", sectionLabel: "Snapshots of You", sortOrder: 74, page: 52, group: "Age Three" },
  { key: "ly_a3_snapshot_3", prompt: "Snapshot 3", size: "4x4", section: "ly_a3_snapshots", sectionLabel: "Snapshots of You", sortOrder: 75, page: 52, group: "Age Three" },
  { key: "ly_a3_snapshot_4", prompt: "Snapshot 4", size: "4x4", section: "ly_a3_snapshots", sectionLabel: "Snapshots of You", sortOrder: 76, page: 52, group: "Age Three" },
  { key: "ly_a3_snapshot_5", prompt: "Snapshot 5", size: "4x4", section: "ly_a3_snapshots", sectionLabel: "Snapshots of You", sortOrder: 77, page: 53, group: "Age Three" },
  { key: "ly_a3_snapshot_6", prompt: "Snapshot 6", size: "4x4", section: "ly_a3_snapshots", sectionLabel: "Snapshots of You", sortOrder: 78, page: 53, group: "Age Three" },
  { key: "ly_a3_snapshot_7", prompt: "Snapshot 7", size: "4x4", section: "ly_a3_snapshots", sectionLabel: "Snapshots of You", sortOrder: 79, page: 53, group: "Age Three" },
  { key: "ly_a3_snapshot_8", prompt: "Snapshot 8", size: "4x4", section: "ly_a3_snapshots", sectionLabel: "Snapshots of You", sortOrder: 80, page: 53, group: "Age Three" },
  { key: "ly_a3_snapshot_9", prompt: "Snapshot 9", size: "4x4", section: "ly_a3_snapshots", sectionLabel: "Snapshots of You", sortOrder: 81, page: 54, group: "Age Three" },
  { key: "ly_a3_snapshot_10", prompt: "Snapshot 10", size: "4x4", section: "ly_a3_snapshots", sectionLabel: "Snapshots of You", sortOrder: 82, page: 54, group: "Age Three" },
  { key: "ly_a3_snapshot_11", prompt: "Snapshot 11", size: "4x4", section: "ly_a3_snapshots", sectionLabel: "Snapshots of You", sortOrder: 83, page: 54, group: "Age Three" },
  { key: "ly_a3_snapshot_12", prompt: "Snapshot 12", size: "4x4", section: "ly_a3_snapshots", sectionLabel: "Snapshots of You", sortOrder: 84, page: 54, group: "Age Three" },
  { key: "ly_a3_snapshot_13", prompt: "Snapshot 13", size: "4x4", section: "ly_a3_snapshots", sectionLabel: "Snapshots of You", sortOrder: 85, page: 55, group: "Age Three" },
  { key: "ly_a3_snapshot_14", prompt: "Snapshot 14", size: "4x4", section: "ly_a3_snapshots", sectionLabel: "Snapshots of You", sortOrder: 86, page: 55, group: "Age Three" },
  { key: "ly_a3_snapshot_15", prompt: "Snapshot 15", size: "4x4", section: "ly_a3_snapshots", sectionLabel: "Snapshots of You", sortOrder: 87, page: 55, group: "Age Three" },
  { key: "ly_a3_snapshot_16", prompt: "Snapshot 16", size: "4x4", section: "ly_a3_snapshots", sectionLabel: "Snapshots of You", sortOrder: 88, page: 55, group: "Age Three" },
  { key: "ly_a4_birthday_1", prompt: "4th Birthday", size: "4x4", section: "ly_a4_birthday", sectionLabel: "Your 4th Birthday", sortOrder: 89, page: 65, group: "Age Four" },
  { key: "ly_a4_birthday_2", prompt: "4th Birthday", size: "4x4", section: "ly_a4_birthday", sectionLabel: "Your 4th Birthday", sortOrder: 90, page: 65, group: "Age Four" },
  { key: "ly_a4_birthday_3", prompt: "4th Birthday", size: "4x4", section: "ly_a4_birthday", sectionLabel: "Your 4th Birthday", sortOrder: 91, page: 65, group: "Age Four" },
  { key: "ly_a4_grown_1", prompt: "Look How You've Grown", size: "4x4", section: "ly_a4_grown", sectionLabel: "Look How You've Grown", sortOrder: 92, page: 66, group: "Age Four" },
  { key: "ly_a4_grown_2", prompt: "Look How You've Grown", size: "4x4", section: "ly_a4_grown", sectionLabel: "Look How You've Grown", sortOrder: 93, page: 66, group: "Age Four" },
  { key: "ly_a4_grown_3", prompt: "Look How You've Grown", size: "4x4", section: "ly_a4_grown", sectionLabel: "Look How You've Grown", sortOrder: 94, page: 66, group: "Age Four" },
  { key: "ly_a4_family", prompt: "Our Family, Age Four", size: "5x5", section: "ly_a4_family", sectionLabel: "Our Family", sortOrder: 95, page: 69, group: "Age Four" },
  { key: "ly_a4_holiday_1", prompt: "Holiday ___", size: "4x4", section: "ly_a4_holidays", sectionLabel: "Holidays", sortOrder: 96, page: 71, group: "Age Four", customLabel: true },
  { key: "ly_a4_holiday_2", prompt: "Holiday ___", size: "4x4", section: "ly_a4_holidays", sectionLabel: "Holidays", sortOrder: 97, page: 71, group: "Age Four", customLabel: true },
  { key: "ly_a4_holiday_3", prompt: "Holiday ___", size: "4x4", section: "ly_a4_holidays", sectionLabel: "Holidays", sortOrder: 98, page: 71, group: "Age Four", customLabel: true },
  { key: "ly_a4_holiday_4", prompt: "Holiday ___", size: "4x4", section: "ly_a4_holidays", sectionLabel: "Holidays", sortOrder: 99, page: 72, group: "Age Four", customLabel: true },
  { key: "ly_a4_holiday_5", prompt: "Holiday ___", size: "4x4", section: "ly_a4_holidays", sectionLabel: "Holidays", sortOrder: 100, page: 72, group: "Age Four", customLabel: true },
  { key: "ly_a4_holiday_6", prompt: "Holiday ___", size: "4x4", section: "ly_a4_holidays", sectionLabel: "Holidays", sortOrder: 101, page: 72, group: "Age Four", customLabel: true },
  { key: "ly_a4_snapshot_1", prompt: "Snapshot 1", size: "4x4", section: "ly_a4_snapshots", sectionLabel: "Snapshots of You", sortOrder: 102, page: 73, group: "Age Four" },
  { key: "ly_a4_snapshot_2", prompt: "Snapshot 2", size: "4x4", section: "ly_a4_snapshots", sectionLabel: "Snapshots of You", sortOrder: 103, page: 73, group: "Age Four" },
  { key: "ly_a4_snapshot_3", prompt: "Snapshot 3", size: "4x4", section: "ly_a4_snapshots", sectionLabel: "Snapshots of You", sortOrder: 104, page: 73, group: "Age Four" },
  { key: "ly_a4_snapshot_4", prompt: "Snapshot 4", size: "4x4", section: "ly_a4_snapshots", sectionLabel: "Snapshots of You", sortOrder: 105, page: 73, group: "Age Four" },
  { key: "ly_a4_snapshot_5", prompt: "Snapshot 5", size: "4x4", section: "ly_a4_snapshots", sectionLabel: "Snapshots of You", sortOrder: 106, page: 74, group: "Age Four" },
  { key: "ly_a4_snapshot_6", prompt: "Snapshot 6", size: "4x4", section: "ly_a4_snapshots", sectionLabel: "Snapshots of You", sortOrder: 107, page: 74, group: "Age Four" },
  { key: "ly_a4_snapshot_7", prompt: "Snapshot 7", size: "4x4", section: "ly_a4_snapshots", sectionLabel: "Snapshots of You", sortOrder: 108, page: 74, group: "Age Four" },
  { key: "ly_a4_snapshot_8", prompt: "Snapshot 8", size: "4x4", section: "ly_a4_snapshots", sectionLabel: "Snapshots of You", sortOrder: 109, page: 74, group: "Age Four" },
  { key: "ly_a4_snapshot_9", prompt: "Snapshot 9", size: "4x4", section: "ly_a4_snapshots", sectionLabel: "Snapshots of You", sortOrder: 110, page: 75, group: "Age Four" },
  { key: "ly_a4_snapshot_10", prompt: "Snapshot 10", size: "4x4", section: "ly_a4_snapshots", sectionLabel: "Snapshots of You", sortOrder: 111, page: 75, group: "Age Four" },
  { key: "ly_a4_snapshot_11", prompt: "Snapshot 11", size: "4x4", section: "ly_a4_snapshots", sectionLabel: "Snapshots of You", sortOrder: 112, page: 75, group: "Age Four" },
  { key: "ly_a4_snapshot_12", prompt: "Snapshot 12", size: "4x4", section: "ly_a4_snapshots", sectionLabel: "Snapshots of You", sortOrder: 113, page: 75, group: "Age Four" },
  { key: "ly_a4_snapshot_13", prompt: "Snapshot 13", size: "4x4", section: "ly_a4_snapshots", sectionLabel: "Snapshots of You", sortOrder: 114, page: 76, group: "Age Four" },
  { key: "ly_a4_snapshot_14", prompt: "Snapshot 14", size: "4x4", section: "ly_a4_snapshots", sectionLabel: "Snapshots of You", sortOrder: 115, page: 76, group: "Age Four" },
  { key: "ly_a4_snapshot_15", prompt: "Snapshot 15", size: "4x4", section: "ly_a4_snapshots", sectionLabel: "Snapshots of You", sortOrder: 116, page: 76, group: "Age Four" },
  { key: "ly_a4_snapshot_16", prompt: "Snapshot 16", size: "4x4", section: "ly_a4_snapshots", sectionLabel: "Snapshots of You", sortOrder: 117, page: 76, group: "Age Four" },
  { key: "ly_a5_birthday_1", prompt: "5th Birthday", size: "4x4", section: "ly_a5_birthday", sectionLabel: "Your 5th Birthday", sortOrder: 118, page: 86, group: "Age Five" },
  { key: "ly_a5_birthday_2", prompt: "5th Birthday", size: "4x4", section: "ly_a5_birthday", sectionLabel: "Your 5th Birthday", sortOrder: 119, page: 86, group: "Age Five" },
  { key: "ly_a5_birthday_3", prompt: "5th Birthday", size: "4x4", section: "ly_a5_birthday", sectionLabel: "Your 5th Birthday", sortOrder: 120, page: 86, group: "Age Five" },
  { key: "ly_a5_grown_1", prompt: "Look How You've Grown", size: "4x4", section: "ly_a5_grown", sectionLabel: "Look How You've Grown", sortOrder: 121, page: 87, group: "Age Five" },
  { key: "ly_a5_grown_2", prompt: "Look How You've Grown", size: "4x4", section: "ly_a5_grown", sectionLabel: "Look How You've Grown", sortOrder: 122, page: 87, group: "Age Five" },
  { key: "ly_a5_grown_3", prompt: "Look How You've Grown", size: "4x4", section: "ly_a5_grown", sectionLabel: "Look How You've Grown", sortOrder: 123, page: 87, group: "Age Five" },
  { key: "ly_a5_family", prompt: "Our Family, Age Five", size: "5x5", section: "ly_a5_family", sectionLabel: "Our Family", sortOrder: 124, page: 90, group: "Age Five" },
  { key: "ly_a5_holiday_1", prompt: "Holiday ___", size: "4x4", section: "ly_a5_holidays", sectionLabel: "Holidays", sortOrder: 125, page: 92, group: "Age Five", customLabel: true },
  { key: "ly_a5_holiday_2", prompt: "Holiday ___", size: "4x4", section: "ly_a5_holidays", sectionLabel: "Holidays", sortOrder: 126, page: 92, group: "Age Five", customLabel: true },
  { key: "ly_a5_holiday_3", prompt: "Holiday ___", size: "4x4", section: "ly_a5_holidays", sectionLabel: "Holidays", sortOrder: 127, page: 92, group: "Age Five", customLabel: true },
  { key: "ly_a5_holiday_4", prompt: "Holiday ___", size: "4x4", section: "ly_a5_holidays", sectionLabel: "Holidays", sortOrder: 128, page: 93, group: "Age Five", customLabel: true },
  { key: "ly_a5_holiday_5", prompt: "Holiday ___", size: "4x4", section: "ly_a5_holidays", sectionLabel: "Holidays", sortOrder: 129, page: 93, group: "Age Five", customLabel: true },
  { key: "ly_a5_holiday_6", prompt: "Holiday ___", size: "4x4", section: "ly_a5_holidays", sectionLabel: "Holidays", sortOrder: 130, page: 93, group: "Age Five", customLabel: true },
  { key: "ly_a5_snapshot_1", prompt: "Snapshot 1", size: "4x4", section: "ly_a5_snapshots", sectionLabel: "Snapshots of You", sortOrder: 131, page: 94, group: "Age Five" },
  { key: "ly_a5_snapshot_2", prompt: "Snapshot 2", size: "4x4", section: "ly_a5_snapshots", sectionLabel: "Snapshots of You", sortOrder: 132, page: 94, group: "Age Five" },
  { key: "ly_a5_snapshot_3", prompt: "Snapshot 3", size: "4x4", section: "ly_a5_snapshots", sectionLabel: "Snapshots of You", sortOrder: 133, page: 94, group: "Age Five" },
  { key: "ly_a5_snapshot_4", prompt: "Snapshot 4", size: "4x4", section: "ly_a5_snapshots", sectionLabel: "Snapshots of You", sortOrder: 134, page: 94, group: "Age Five" },
  { key: "ly_a5_snapshot_5", prompt: "Snapshot 5", size: "4x4", section: "ly_a5_snapshots", sectionLabel: "Snapshots of You", sortOrder: 135, page: 95, group: "Age Five" },
  { key: "ly_a5_snapshot_6", prompt: "Snapshot 6", size: "4x4", section: "ly_a5_snapshots", sectionLabel: "Snapshots of You", sortOrder: 136, page: 95, group: "Age Five" },
  { key: "ly_a5_snapshot_7", prompt: "Snapshot 7", size: "4x4", section: "ly_a5_snapshots", sectionLabel: "Snapshots of You", sortOrder: 137, page: 95, group: "Age Five" },
  { key: "ly_a5_snapshot_8", prompt: "Snapshot 8", size: "4x4", section: "ly_a5_snapshots", sectionLabel: "Snapshots of You", sortOrder: 138, page: 95, group: "Age Five" },
  { key: "ly_a5_snapshot_9", prompt: "Snapshot 9", size: "4x4", section: "ly_a5_snapshots", sectionLabel: "Snapshots of You", sortOrder: 139, page: 96, group: "Age Five" },
  { key: "ly_a5_snapshot_10", prompt: "Snapshot 10", size: "4x4", section: "ly_a5_snapshots", sectionLabel: "Snapshots of You", sortOrder: 140, page: 96, group: "Age Five" },
  { key: "ly_a5_snapshot_11", prompt: "Snapshot 11", size: "4x4", section: "ly_a5_snapshots", sectionLabel: "Snapshots of You", sortOrder: 141, page: 96, group: "Age Five" },
  { key: "ly_a5_snapshot_12", prompt: "Snapshot 12", size: "4x4", section: "ly_a5_snapshots", sectionLabel: "Snapshots of You", sortOrder: 142, page: 96, group: "Age Five" },
  { key: "ly_a5_snapshot_13", prompt: "Snapshot 13", size: "4x4", section: "ly_a5_snapshots", sectionLabel: "Snapshots of You", sortOrder: 143, page: 97, group: "Age Five" },
  { key: "ly_a5_snapshot_14", prompt: "Snapshot 14", size: "4x4", section: "ly_a5_snapshots", sectionLabel: "Snapshots of You", sortOrder: 144, page: 97, group: "Age Five" },
  { key: "ly_a5_snapshot_15", prompt: "Snapshot 15", size: "4x4", section: "ly_a5_snapshots", sectionLabel: "Snapshots of You", sortOrder: 145, page: 97, group: "Age Five" },
  { key: "ly_a5_snapshot_16", prompt: "Snapshot 16", size: "4x4", section: "ly_a5_snapshots", sectionLabel: "Snapshots of You", sortOrder: 146, page: 97, group: "Age Five" },
];
